spring:
  application:
    name: rag-app-back
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW # On force l'indexation haute performance !
        distance-type: cosine_distance
        initialize-schema: true
    ollama:
      chat:
        options:
          model: llama3
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text
  datasource:
    url: jdbc:postgresql://localhost:5433/rag-app-db
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  chat:
    history-size: 5
